/**
 * SSO routes — cross-app "foreign user" authentication between Obliview and Obliguard.
 *
 * Endpoints exposed FOR the other app (Bearer auth = shared Obliguard secret):
 *   GET  /api/sso/validate-token?token=xxx   — validate a switch token generated by Obliview
 *   GET  /api/sso/users                      — list Obliview users (for admin pre-assignment)
 *
 * Endpoints used BY Obliview's own client (session auth):
 *   POST /api/sso/generate-token             — generate a one-time switch token for current user
 *   POST /api/sso/set-password               — set a local password for foreign user (first-login)
 *
 * Endpoint called by Obliview client after arriving from another app (no auth — IS the auth step):
 *   POST /api/sso/exchange                   — exchange an incoming token from another app
 */

import crypto from 'crypto';
import { Router } from 'express';
import type { Request, Response, NextFunction } from 'express';
import { requireAuth } from '../middleware/auth';
import { appConfigService } from '../services/appConfig.service';
import { authService } from '../services/auth.service';
import { hashPassword } from '../utils/crypto';
import { tenantService } from '../services/tenant.service';
import { AppError } from '../middleware/errorHandler';
import { db } from '../db';

const router = Router();

// ─────────────────────────────────────────────────────────────────────────────
// Helper: Bearer auth check against the configured Obliguard shared secret
// ─────────────────────────────────────────────────────────────────────────────
async function requireSsoBearer(req: Request, res: Response): Promise<boolean> {
  const cfg = await appConfigService.getObliguardConfig();
  if (!cfg?.apiKey) {
    res.status(503).json({ success: false, error: 'SSO not configured' });
    return false;
  }
  const auth = req.headers.authorization ?? '';
  const token = auth.startsWith('Bearer ') ? auth.slice(7) : '';
  if (!token || token !== cfg.apiKey) {
    res.status(401).json({ success: false, error: 'Unauthorized' });
    return false;
  }
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper: check that enable_foreign_sso is on
// ─────────────────────────────────────────────────────────────────────────────
async function requireSsoEnabled(res: Response): Promise<boolean> {
  const cfg = await appConfigService.getAll();
  if (!cfg.enable_foreign_sso) {
    res.status(403).json({ success: false, error: 'SSO not enabled' });
    return false;
  }
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// Periodic cleanup of expired tokens (runs inline, max every 5 min)
// ─────────────────────────────────────────────────────────────────────────────
let lastCleanup = 0;
async function cleanupExpiredTokens() {
  const now = Date.now();
  if (now - lastCleanup < 5 * 60 * 1000) return;
  lastCleanup = now;
  await db('sso_tokens').where('expires_at', '<', new Date()).delete();
}

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/sso/generate-token
// Obliview client calls this when user clicks "⇄ Obliguard".
// Generates a one-time 60s token and returns it; client then redirects to the
// other app's /auth/foreign page with it.
// ─────────────────────────────────────────────────────────────────────────────
router.post('/generate-token', requireAuth, async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    if (!await requireSsoEnabled(res)) return;
    await cleanupExpiredTokens();

    const userId = req.session.userId!;
    const token = crypto.randomBytes(32).toString('hex'); // 64-char hex
    const expiresAt = new Date(Date.now() + 60_000); // 60 seconds

    await db('sso_tokens').insert({ token, user_id: userId, expires_at: expiresAt });

    res.json({ success: true, data: { token } });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/sso/validate-token?token=xxx
// Called BY the other app (Obliguard) with Bearer auth.
// Validates the token and returns the user's public info.
// ─────────────────────────────────────────────────────────────────────────────
router.get('/validate-token', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    if (!await requireSsoEnabled(res)) return;
    if (!await requireSsoBearer(req, res)) return;

    const { token } = req.query as { token?: string };
    if (!token) { res.status(400).json({ success: false, error: 'token is required' }); return; }

    const row = await db('sso_tokens')
      .where({ token, used: false })
      .where('expires_at', '>', new Date())
      .first() as { id: number; user_id: number } | undefined;

    if (!row) { res.status(404).json({ success: false, error: 'Token not found or expired' }); return; }

    // Mark as used (one-time)
    await db('sso_tokens').where({ id: row.id }).update({ used: true });

    const user = await authService.getUserById(row.user_id);
    if (!user || !user.isActive) { res.status(404).json({ success: false, error: 'User not found' }); return; }

    // Use { user: { ... } } format — symmetric with Obliguard's validate-token response format.
    res.json({
      user: {
        id: user.id,
        username: user.username,
        displayName: user.displayName ?? null,
        email: user.email ?? null,
        role: user.role,
      },
    });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/sso/users
// Called BY the other app (Obliguard) with Bearer auth.
// Returns list of Obliview users for admin pre-assignment of permissions.
// ─────────────────────────────────────────────────────────────────────────────
router.get('/users', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    if (!await requireSsoEnabled(res)) return;
    if (!await requireSsoBearer(req, res)) return;

    const users = await db('users')
      .where({ is_active: true })
      .whereNull('foreign_source') // only expose local Obliview users
      .select('id', 'username', 'email', 'role', 'display_name');

    res.json({
      success: true,
      data: users.map((u: { id: number; username: string; email: string | null; role: string; display_name: string | null }) => ({
        id: u.id,
        username: u.username,
        email: u.email ?? null,
        role: u.role,
        displayName: u.display_name ?? null,
      })),
    });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/sso/exchange  { token: string, from: string }
// Called BY Obliview's OWN client after the user arrives from the other app.
// No session auth — this IS the authentication step.
// ─────────────────────────────────────────────────────────────────────────────
router.post('/exchange', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    if (!await requireSsoEnabled(res)) return;

    const { token, from } = req.body as { token?: string; from?: string };
    if (!token || !from) throw new AppError(400, 'token and from are required');

    // Security: validate that `from` matches the configured Obliguard URL
    const cfg = await appConfigService.getObliguardConfig();
    if (!cfg?.url || !cfg?.apiKey) throw new AppError(503, 'SSO not configured');

    const normalise = (u: string) => u.replace(/\/$/, '').toLowerCase();
    if (normalise(from) !== normalise(cfg.url)) {
      throw new AppError(403, 'Unknown SSO source');
    }

    // Call Obliguard's validate-token endpoint (symmetric path: both apps use /api/sso/validate-token).
    const base = cfg.url.replace(/\/$/, '');
    let fetchRes: Awaited<ReturnType<typeof fetch>>;
    try {
      fetchRes = await fetch(`${base}/api/sso/validate-token?token=${encodeURIComponent(token)}`, {
        headers: { Authorization: `Bearer ${cfg.apiKey}` },
        signal: AbortSignal.timeout(8000),
      });
    } catch (fetchErr) {
      console.error('[sso exchange] Network error calling Obliguard:', fetchErr);
      throw new AppError(502, 'Could not reach SSO source');
    }

    if (!fetchRes.ok) {
      const text = await fetchRes.text().catch(() => '');
      console.error(`[sso exchange] Source returned HTTP ${fetchRes.status}: ${text}`);
      throw new AppError(401, 'Invalid or expired SSO token');
    }

    const body = await fetchRes.json() as {
      user?: { id: number; username: string; displayName?: string | null; email?: string | null; role: string };
    };
    if (!body.user) throw new AppError(401, 'Invalid SSO response');

    const { id: foreignId, username, email, role: _role } = body.user;

    // Find or create the local foreign user
    const { user, isFirstLogin } = await authService.findOrCreateForeignUser(
      'obliguard',
      foreignId,
      base,
      { username, email },
    );

    // Establish session
    req.session.userId = user.id;
    req.session.username = user.username;
    req.session.role = user.role;

    // Resolve tenant
    const tenant = await tenantService.getFirstTenantForUser(user.id);
    req.session.currentTenantId = tenant?.id ?? 1;

    res.json({ success: true, data: { user, isFirstLogin } });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/sso/set-password  { password: string }
// Called after first SSO login if the user wants a local password.
// Only works for foreign users who currently have no local password.
// ─────────────────────────────────────────────────────────────────────────────
router.post('/set-password', requireAuth, async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const userId = req.session.userId!;
    const { password } = req.body as { password?: string };
    if (!password || password.length < 8) throw new AppError(400, 'Password must be at least 8 characters');

    const row = await db('users').where({ id: userId }).first() as { password_hash: string | null } | undefined;
    if (!row) throw new AppError(404, 'User not found');
    if (row.password_hash) throw new AppError(409, 'User already has a local password');

    const hash = await hashPassword(password);
    await db('users').where({ id: userId }).update({ password_hash: hash, updated_at: new Date() });

    res.json({ success: true });
  } catch (err) {
    next(err);
  }
});

export default router;
