/**
 * SSO routes — cross-app "foreign user" authentication between Obliview and Obliguard.
 *
 * Endpoints exposed FOR the other app (Bearer auth = shared Obliguard secret):
 *   GET  /api/sso/validate-token?token=xxx   — validate a switch token generated by Obliview
 *   GET  /api/sso/users                      — list Obliview users (for admin pre-assignment)
 *
 * Endpoints used BY Obliview's own client (session auth):
 *   POST /api/sso/generate-token             — generate a one-time switch token for current user
 *   POST /api/sso/set-password               — set a local password for foreign user (first-login)
 *
 * Endpoint called by Obliview client after arriving from another app (no auth — IS the auth step):
 *   POST /api/sso/exchange                   — exchange an incoming token from another app
 */

import crypto from 'crypto';
import { Router } from 'express';
import type { Request, Response, NextFunction } from 'express';
import { requireAuth } from '../middleware/auth';
import { appConfigService } from '../services/appConfig.service';
import { authService, AccountLinkRequiredError } from '../services/auth.service';
import { twoFactorService } from '../services/twoFactor.service';
import { hashPassword, comparePassword } from '../utils/crypto';
import { tenantService } from '../services/tenant.service';
import { AppError } from '../middleware/errorHandler';
import { db } from '../db';

const router = Router();

// ─────────────────────────────────────────────────────────────────────────────
// Helper: Bearer auth — accept the shared API key from ANY configured source
// (Obliguard, Oblimap, or Obliance) so all three can call validate-token.
// ─────────────────────────────────────────────────────────────────────────────
async function requireSsoBearer(req: Request, res: Response): Promise<boolean> {
  const [obliguardCfg, oblimapCfg, oblianceCfg] = await Promise.all([
    appConfigService.getObliguardConfig(),
    appConfigService.getOblimapConfig(),
    appConfigService.getOblianceConfig(),
  ]);

  const validKeys = [obliguardCfg?.apiKey, oblimapCfg?.apiKey, oblianceCfg?.apiKey]
    .filter((k): k is string => !!k);

  if (validKeys.length === 0) {
    res.status(503).json({ success: false, error: 'SSO not configured' });
    return false;
  }

  const auth = req.headers.authorization ?? '';
  const bearer = auth.startsWith('Bearer ') ? auth.slice(7) : '';
  if (!bearer || !validKeys.includes(bearer)) {
    res.status(401).json({ success: false, error: 'Unauthorized' });
    return false;
  }
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper: check that enable_foreign_sso is on
// ─────────────────────────────────────────────────────────────────────────────
async function requireSsoEnabled(res: Response): Promise<boolean> {
  const cfg = await appConfigService.getAll();
  if (!cfg.enable_foreign_sso) {
    res.status(403).json({ success: false, error: 'SSO not enabled' });
    return false;
  }
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// Periodic cleanup of expired tokens (runs inline, max every 5 min)
// ─────────────────────────────────────────────────────────────────────────────
let lastCleanup = 0;
async function cleanupExpiredTokens() {
  const now = Date.now();
  if (now - lastCleanup < 5 * 60 * 1000) return;
  lastCleanup = now;
  await db('sso_tokens').where('expires_at', '<', new Date()).delete();
}

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/sso/generate-token
// Obliview client calls this when user clicks "⇄ Obliguard".
// Generates a one-time 60s token and returns it; client then redirects to the
// other app's /auth/foreign page with it.
// ─────────────────────────────────────────────────────────────────────────────
router.post('/generate-token', requireAuth, async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    if (!await requireSsoEnabled(res)) return;
    await cleanupExpiredTokens();

    const userId = req.session.userId!;
    const token = crypto.randomBytes(32).toString('hex'); // 64-char hex
    const expiresAt = new Date(Date.now() + 60_000); // 60 seconds

    await db('sso_tokens').insert({ token, user_id: userId, expires_at: expiresAt });

    res.json({ success: true, data: { token } });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/sso/validate-token?token=xxx
// Called BY the other app (Obliguard) with Bearer auth.
// Validates the token and returns the user's public info.
// ─────────────────────────────────────────────────────────────────────────────
router.get('/validate-token', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    console.log('[sso validate-token] incoming request from', req.ip, '— auth:', req.headers.authorization ? 'present' : 'MISSING');
    if (!await requireSsoEnabled(res)) { console.log('[sso validate-token] SSO not enabled'); return; }
    if (!await requireSsoBearer(req, res)) { console.log('[sso validate-token] Bearer auth failed'); return; }

    const { token } = req.query as { token?: string };
    if (!token) { res.status(400).json({ success: false, error: 'token is required' }); return; }

    // Atomically mark the token as used in a single UPDATE — prevents race conditions
    // where two concurrent requests both read used=false before either writes used=true.
    const [row] = await db('sso_tokens')
      .where({ token, used: false })
      .where('expires_at', '>', new Date())
      .update({ used: true })
      .returning(['id', 'user_id']) as { id: number; user_id: number }[];

    if (!row) { res.status(404).json({ success: false, error: 'Token not found or expired' }); return; }

    const user = await authService.getUserById(row.user_id);
    if (!user || !user.isActive) { res.status(404).json({ success: false, error: 'User not found' }); return; }

    // Use { success, data: { user } } format — matches what Obliguard's exchange expects.
    res.json({
      success: true,
      data: {
        user: {
          id: user.id,
          username: user.username,
          displayName: user.displayName ?? null,
          email: user.email ?? null,
          role: user.role,
        },
      },
    });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/sso/users
// Called BY the other app (Obliguard) with Bearer auth.
// Returns list of Obliview users for admin pre-assignment of permissions.
// ─────────────────────────────────────────────────────────────────────────────
router.get('/users', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    if (!await requireSsoEnabled(res)) return;
    if (!await requireSsoBearer(req, res)) return;

    const users = await db('users')
      .where({ is_active: true })
      .whereNull('foreign_source') // only expose local Obliview users
      .select('id', 'username', 'email', 'role', 'display_name');

    res.json({
      success: true,
      data: users.map((u: { id: number; username: string; email: string | null; role: string; display_name: string | null }) => ({
        id: u.id,
        username: u.username,
        email: u.email ?? null,
        role: u.role,
        displayName: u.display_name ?? null,
      })),
    });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/sso/exchange  { token: string, from: string }
// Called BY Obliview's OWN client after the user arrives from the other app.
// No session auth — this IS the authentication step.
// ─────────────────────────────────────────────────────────────────────────────
router.post('/exchange', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    if (!await requireSsoEnabled(res)) return;

    const { token, from } = req.body as { token?: string; from?: string };
    if (!token || !from) throw new AppError(400, 'token and from are required');

    // Resolve which source app this token came from
    const normalise = (u: string) => u.replace(/\/$/, '').toLowerCase();
    const fromNorm = normalise(from);

    const [obliguardCfg, oblimapCfg, oblianceCfg] = await Promise.all([
      appConfigService.getObliguardConfig(),
      appConfigService.getOblimapConfig(),
      appConfigService.getOblianceConfig(),
    ]);

    type SourceEntry = { name: string; url: string; apiKey: string };
    const sources: SourceEntry[] = [];
    if (obliguardCfg?.url && obliguardCfg?.apiKey) sources.push({ name: 'obliguard', url: obliguardCfg.url, apiKey: obliguardCfg.apiKey });
    if (oblimapCfg?.url  && oblimapCfg?.apiKey)   sources.push({ name: 'oblimap',   url: oblimapCfg.url,   apiKey: oblimapCfg.apiKey   });
    if (oblianceCfg?.url && oblianceCfg?.apiKey)  sources.push({ name: 'obliance',  url: oblianceCfg.url,  apiKey: oblianceCfg.apiKey  });

    const source = sources.find((s) => normalise(s.url) === fromNorm);
    if (!source) {
      console.warn(`[sso exchange] Unknown SSO source: from=${from}, known urls=${sources.map((s) => s.url).join(', ')}`);
      throw new AppError(403, 'Unknown SSO source');
    }

    // Call the source app's validate-token endpoint
    const base = source.url.replace(/\/$/, '');
    let fetchRes: Awaited<ReturnType<typeof fetch>>;
    try {
      fetchRes = await fetch(`${base}/api/sso/validate-token?token=${encodeURIComponent(token)}`, {
        headers: { Authorization: `Bearer ${source.apiKey}` },
        signal: AbortSignal.timeout(8000),
      });
    } catch (fetchErr) {
      console.error(`[sso exchange] Network error calling ${source.name}:`, fetchErr);
      throw new AppError(502, 'Could not reach SSO source');
    }

    if (!fetchRes.ok) {
      const text = await fetchRes.text().catch(() => '');
      console.error(`[sso exchange] ${source.name} returned HTTP ${fetchRes.status}: ${text}`);
      throw new AppError(401, 'Invalid or expired SSO token');
    }

    const body = await fetchRes.json() as {
      success: boolean;
      data?: { user: { id: number; username: string; displayName?: string | null; email?: string | null; role: string } };
    };
    if (!body.success || !body.data?.user) throw new AppError(401, 'Invalid SSO response');

    const { id: foreignId, username, email, role: _role } = body.data.user;

    // Find or create the local foreign user
    let user: Awaited<ReturnType<typeof authService.getUserById>>;
    let isFirstLogin: boolean;
    try {
      const result = await authService.findOrCreateForeignUser(
        source.name,
        foreignId,
        base,
        { username, email },
      );
      user = result.user;
      isFirstLogin = result.isFirstLogin;
    } catch (findErr) {
      if (findErr instanceof AccountLinkRequiredError) {
        // Username belongs to an existing local account — issue a link token.
        const linkToken = crypto.randomBytes(32).toString('hex');
        await db('sso_link_tokens').insert({
          link_token: linkToken,
          foreign_source: source.name,
          foreign_id: foreignId,
          foreign_source_url: base,
          foreign_username: username,
          foreign_display_name: body.data.user.displayName ?? null,
          foreign_role: _role,
          foreign_email: email ?? null,
          conflicting_username: findErr.conflictingUsername,
          expires_at: new Date(Date.now() + 5 * 60_000),
        });
        res.json({ success: true, data: { needsLinking: true, linkToken, conflictingUsername: findErr.conflictingUsername } });
        return;
      }
      throw findErr;
    }

    // Establish session
    req.session.userId = user!.id;
    req.session.username = user!.username;
    req.session.role = user!.role;

    // Resolve tenant
    const tenant = await tenantService.getFirstTenantForUser(user!.id);
    req.session.currentTenantId = tenant?.id ?? 1;

    res.json({ success: true, data: { user, isFirstLogin } });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/sso/complete-link  { linkToken: string, password: string }
// Verifies local password. If the account has 2FA, returns { requires2fa: true }
// and stores a pending session — client must then call /verify-link-2fa.
// No session auth — this IS the authentication step.
// ─────────────────────────────────────────────────────────────────────────────
router.post('/complete-link', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const { linkToken, password } = req.body as { linkToken?: string; password?: string };
    if (!linkToken || !password) throw new AppError(400, 'linkToken and password are required');

    const linkRow = await db('sso_link_tokens')
      .where({ link_token: linkToken })
      .where('expires_at', '>', new Date())
      .first() as {
        foreign_source: string; foreign_id: number; foreign_source_url: string;
        conflicting_username: string;
      } | undefined;
    if (!linkRow) throw new AppError(401, 'Link token expired or invalid');

    const localUser = await db('users')
      .where({ username: linkRow.conflicting_username, is_active: true })
      .first() as {
        id: number; username: string; role: string; password_hash: string | null;
        totp_enabled: boolean | null; email_otp_enabled: boolean | null; email: string | null;
      } | undefined;
    if (!localUser || !localUser.password_hash) throw new AppError(404, 'Local account not found');

    const valid = await comparePassword(password, localUser.password_hash);
    if (!valid) throw new AppError(401, 'Incorrect password');

    // If the local account has 2FA, require it before completing the link
    const hasMfa = localUser.totp_enabled || localUser.email_otp_enabled;
    if (hasMfa) {
      req.session.pendingMfaLinkToken = linkToken;

      // Auto-send email OTP if configured
      if (localUser.email_otp_enabled && localUser.email) {
        const cfg = await appConfigService.getAll();
        if (cfg.otp_smtp_server_id) {
          const code = twoFactorService.generateEmailOtp();
          req.session.pendingEmailOtp = { code, email: localUser.email, expires: Date.now() + 10 * 60 * 1000 };
          await twoFactorService.sendEmailOtp(cfg.otp_smtp_server_id, localUser.email, code);
        }
      }

      res.json({
        success: true,
        data: {
          requires2fa: true,
          methods: { totp: !!localUser.totp_enabled, email: !!localUser.email_otp_enabled },
        },
      });
      return;
    }

    // No 2FA — complete the link immediately
    await db('users').where({ id: localUser.id }).update({
      foreign_source: linkRow.foreign_source,
      foreign_id: linkRow.foreign_id,
      foreign_source_url: linkRow.foreign_source_url,
      updated_at: new Date(),
    });
    await db('sso_link_tokens').where({ link_token: linkToken }).delete();

    req.session.userId = localUser.id;
    req.session.username = localUser.username;
    req.session.role = localUser.role;
    const tenant = await tenantService.getFirstTenantForUser(localUser.id);
    req.session.currentTenantId = tenant?.id ?? 1;

    const user = await authService.getUserById(localUser.id);
    res.json({ success: true, data: { user, isFirstLogin: false } });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/sso/verify-link-2fa  { code: string, method: 'totp'|'email', resend?: boolean }
// Second step of the link flow when the local account has 2FA.
// Session must contain pendingMfaLinkToken set by /complete-link.
// ─────────────────────────────────────────────────────────────────────────────
router.post('/verify-link-2fa', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const { code, method, resend } = req.body as { code?: string; method?: string; resend?: boolean };

    const linkToken = req.session.pendingMfaLinkToken;
    if (!linkToken) throw new AppError(400, 'No pending 2FA link session');

    const linkRow = await db('sso_link_tokens')
      .where({ link_token: linkToken })
      .where('expires_at', '>', new Date())
      .first() as {
        foreign_source: string; foreign_id: number; foreign_source_url: string;
        conflicting_username: string;
      } | undefined;
    if (!linkRow) throw new AppError(401, 'Link session expired, please start over');

    const localUser = await db('users')
      .where({ username: linkRow.conflicting_username, is_active: true })
      .first() as {
        id: number; username: string; role: string;
        totp_enabled: boolean | null; totp_secret: string | null;
        email_otp_enabled: boolean | null; email: string | null;
      } | undefined;
    if (!localUser) throw new AppError(404, 'Local account not found');

    // Resend email OTP
    if (resend) {
      if (!localUser.email_otp_enabled || !localUser.email) throw new AppError(400, 'Email OTP not configured for this account');
      const cfg = await appConfigService.getAll();
      if (!cfg.otp_smtp_server_id) throw new AppError(400, 'No SMTP server configured for OTP');
      const newCode = twoFactorService.generateEmailOtp();
      req.session.pendingEmailOtp = { code: newCode, email: localUser.email, expires: Date.now() + 10 * 60 * 1000 };
      await twoFactorService.sendEmailOtp(cfg.otp_smtp_server_id, localUser.email, newCode);
      res.json({ success: true });
      return;
    }

    if (!code || !method) throw new AppError(400, 'code and method are required');

    let valid = false;
    if (method === 'totp' && localUser.totp_enabled && localUser.totp_secret) {
      valid = twoFactorService.verifyTotp(localUser.totp_secret, String(code));
    } else if (method === 'email' && localUser.email_otp_enabled) {
      const pending = req.session.pendingEmailOtp;
      if (pending && Date.now() <= pending.expires && pending.code === String(code)) {
        valid = true;
      }
    }
    if (!valid) throw new AppError(401, 'Invalid code');

    // Complete the link
    await db('users').where({ id: localUser.id }).update({
      foreign_source: linkRow.foreign_source,
      foreign_id: linkRow.foreign_id,
      foreign_source_url: linkRow.foreign_source_url,
      updated_at: new Date(),
    });
    await db('sso_link_tokens').where({ link_token: linkToken }).delete();

    delete req.session.pendingMfaLinkToken;
    delete req.session.pendingEmailOtp;

    req.session.userId = localUser.id;
    req.session.username = localUser.username;
    req.session.role = localUser.role;
    const tenant2fa = await tenantService.getFirstTenantForUser(localUser.id);
    req.session.currentTenantId = tenant2fa?.id ?? 1;

    const user = await authService.getUserById(localUser.id);
    res.json({ success: true, data: { user, isFirstLogin: false } });
  } catch (err) {
    next(err);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/sso/set-password  { password: string }
// Called after first SSO login if the user wants a local password.
// Only works for foreign users who currently have no local password.
// ─────────────────────────────────────────────────────────────────────────────
router.post('/set-password', requireAuth, async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const userId = req.session.userId!;
    const { password } = req.body as { password?: string };
    if (!password || password.length < 8) throw new AppError(400, 'Password must be at least 8 characters');

    const row = await db('users').where({ id: userId }).first() as { password_hash: string | null } | undefined;
    if (!row) throw new AppError(404, 'User not found');
    if (row.password_hash) throw new AppError(409, 'User already has a local password');

    const hash = await hashPassword(password);
    await db('users').where({ id: userId }).update({ password_hash: hash, updated_at: new Date() });

    res.json({ success: true });
  } catch (err) {
    next(err);
  }
});

export default router;
