//go:build darwin

package main

/*
#cgo CFLAGS: -x objective-c
#cgo LDFLAGS: -framework Cocoa

#import <Cocoa/Cocoa.h>

// Set the Dock icon from raw PNG bytes embedded in the binary.
// On macOS, apps don't show an icon in the title bar — the Dock icon
// is the standard representation shown in the Dock and the App Switcher.
static void apply_dock_icon(const unsigned char *data, int len) {
	@autoreleasepool {
		NSData   *nsdata = [NSData dataWithBytes:data length:(NSUInteger)len];
		NSImage  *img    = [[NSImage alloc] initWithData:nsdata];
		if (img) {
			[NSApp setApplicationIconImage:img];
		}
	}
}
*/
import "C"
import (
	_ "embed"
	"unsafe"
)

// logo.png is the 256×256 app icon, generated by the build script from logo.webp.
// It is embedded at compile time so the binary is fully self-contained.
//
//go:embed logo.png
var logoPNG []byte

func applyWindowIcon(_ unsafe.Pointer) {
	if len(logoPNG) == 0 {
		return
	}
	C.apply_dock_icon((*C.uchar)(unsafe.Pointer(&logoPNG[0])), C.int(len(logoPNG)))
}
