//go:build darwin

package main

/*
#cgo CFLAGS: -x objective-c
#cgo LDFLAGS: -framework Cocoa

#import <Cocoa/Cocoa.h>

// Set the Dock icon from raw PNG bytes embedded in the binary.
// On macOS, apps don't show an icon in the title bar — the Dock icon
// is the standard representation shown in the Dock and the App Switcher.
static void apply_dock_icon(const unsigned char *data, int len) {
	@autoreleasepool {
		NSData   *nsdata = [NSData dataWithBytes:data length:(NSUInteger)len];
		NSImage  *img    = [[NSImage alloc] initWithData:nsdata];
		if (img) {
			[NSApp setApplicationIconImage:img];
		}
	}
}

// setup_macos_menu installs a minimal NSMenu on NSApp so that the standard
// macOS keyboard shortcuts are dispatched correctly to WKWebView.
//
// Without a main menu, NSApplication has no key-equivalent bindings and
// simply beeps when the user presses Cmd+C, Cmd+V, Cmd+Q, etc.  Adding a
// proper Application menu (Quit) and Edit menu (Cut/Copy/Paste/Select All/
// Undo/Redo) restores the expected behaviour for a native GUI app.
static void setup_macos_menu(void) {
	@autoreleasepool {
		NSMenu *mainMenu = [NSMenu new];

		// ── Application menu (index 0 — title is ignored by macOS) ──────────
		NSMenuItem *appItem = [mainMenu addItemWithTitle:@"Application"
		                                          action:nil
		                                   keyEquivalent:@""];
		NSMenu *appMenu = [NSMenu new];
		[appItem setSubmenu:appMenu];

		[appMenu addItemWithTitle:@"Quit Obli.tools"
		                   action:@selector(terminate:)
		            keyEquivalent:@"q"];

		// ── Edit menu ────────────────────────────────────────────────────────
		NSMenuItem *editItem = [mainMenu addItemWithTitle:@"Edit"
		                                           action:nil
		                                    keyEquivalent:@""];
		NSMenu *editMenu = [[NSMenu alloc] initWithTitle:@"Edit"];
		[editItem setSubmenu:editMenu];

		[editMenu addItemWithTitle:@"Undo"
		                    action:@selector(undo:)
		             keyEquivalent:@"z"];

		// Redo: Cmd+Shift+Z
		NSMenuItem *redo = [[NSMenuItem alloc] initWithTitle:@"Redo"
		                                              action:@selector(redo:)
		                                       keyEquivalent:@"z"];
		[redo setKeyEquivalentModifierMask:NSEventModifierFlagCommand |
		                                   NSEventModifierFlagShift];
		[editMenu addItem:redo];

		[editMenu addItem:[NSMenuItem separatorItem]];

		[editMenu addItemWithTitle:@"Cut"
		                    action:@selector(cut:)
		             keyEquivalent:@"x"];
		[editMenu addItemWithTitle:@"Copy"
		                    action:@selector(copy:)
		             keyEquivalent:@"c"];
		[editMenu addItemWithTitle:@"Paste"
		                    action:@selector(paste:)
		             keyEquivalent:@"v"];
		[editMenu addItemWithTitle:@"Select All"
		                    action:@selector(selectAll:)
		             keyEquivalent:@"a"];

		[NSApp setMainMenu:mainMenu];
	}
}
*/
import "C"
import (
	_ "embed"
	"unsafe"
)

// logo.png is the 256×256 app icon, generated by the build script from logo.webp.
// It is embedded at compile time so the binary is fully self-contained.
//
//go:embed logo.png
var logoPNG []byte

func applyWindowIcon(_ unsafe.Pointer) {
	if len(logoPNG) == 0 {
		return
	}
	C.apply_dock_icon((*C.uchar)(unsafe.Pointer(&logoPNG[0])), C.int(len(logoPNG)))

	// Install the standard macOS menu so that Cmd+C, Cmd+V, Cmd+Q, etc. work
	// inside WKWebView.  Must be called after webview.New() has initialised NSApp.
	C.setup_macos_menu()
}
